# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/0e2d0f4b-688c-4a38-a222-6965b4b1d387";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-daf86e61-1fa2-4ae7-9aee-3e3e419a2cad".device = "/dev/disk/by-uuid/daf86e61-1fa2-4ae7-9aee-3e3e419a2cad";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/37E9-666E";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/f44e53e8-d476-4f80-8f8e-6d2b967c1eb8"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
